### ISSUE TITLE
Add XMSS

### ISSUE THREAD

**Issue by dingens** [cryptoeng/pqdb#10]

**Comment by dingens** [comment]
I've added some data in #19, but it's difficult because the paper isn't like what we're used to because it is no NIST candidate (it's already RFC standardized). There's no real info about secret key size, for example, and I didn't find benchmarks. Maybe we have to wait for more real-world implementations of this (however it seems people are not very interested in implementing it)

**Comment by franziskuskiefer** [comment]
What's the state of this?

**Comment by benj-zen** [comment]
Added by #19
