### ISSUE TITLE
Add Round 3 info

### ISSUE THREAD

**Issue by dingens** [cryptoeng/pqdb#139]
we should update round information. As there are now two categories, we cannot just put `nist round: 3`.

**Comment by dingens** [comment]
First thoughts: We could make this field a string and then set
- `2`, `3f`(finalist), `3a` (alternate)  (using a tooltip in UI where possible)
- `2`, `F`, `A` (dito)
- something longer like `2`, `finalist`, `alternate` or something

Opinions?

**Comment by taudor** [comment]
I don't like just `3f`, it's a little short. And `3a` could be the first choice, like in `3a` and `3b`.
I would prefer something longer like `3 (fin.)` and `3 (alt.)` with a longer tooltip in the UI.

**Comment by dingens** [comment]
I'm in favor of the first idea. We're using more verbose wording in the frontend anyways (https://cryptoeng.github.io/pqdb/detail?_=sig/18 https://cryptoeng.github.io/pqdb/detail?_=sig/15) and not the direct string from the yaml file. So it'd be an enum `0, 1, 2, 3a, 3f`. (Or maybe with `none` instead of `0`)

**Comment by TomerHawk** [comment]
I like this idea 
> something longer like 2, finalist, alternate or something
because the information is the clearest. 
But if we would choose to use strings in the "round"-field, it would probably make sense to use a string instead of "2" to not irritated the user, or to delete the round 2 sig's/ enc's.

**Comment by TomerHawk** [comment]
I like the idea with strings, because it is simple and fast to interpret them

**Comment by taudor** [comment]
> I'm in favor of the first idea. We're using more verbose wording in the frontend anyways (https://cryptoeng.github.io/pqdb/detail?_=sig/18 https://cryptoeng.github.io/pqdb/detail?_=sig/15) and not the direct string from the yaml file.

That's true, let's use `3a`,`3f` then.

> So it'd be an enum `0, 1, 2, 3a, 3f`. (Or maybe with `none` instead of `0`)

If we're using strings I'm in favour of `none`.
