### ISSUE TITLE
Enter data: Name vs. folder name

### ISSUE THREAD

**Issue by dingens** [cryptoeng/pqdb#33]
The enter data helper asks for a "name" of a scheme. However, this is not really the name, but just the folder name (and should hence be short (and A-z0-9), while inside the yaml file there is another `name` field which is the "real" human readable name.

We should use different wordings for both to avoid confusion.

some ideas:
- short_name / name
- identifier / name

**Comment by benj-zen** [comment]
Yeah, I agree. I think `identifier` is a good choice.
