### ISSUE TITLE
[enter-data-helper] listens on external IP

### ISSUE THREAD

**Issue by dingens** [cryptoeng/pqdb#40]
The electron server is not only listening on localhost, but is accessible from external devices. This could have security implications.

(It would be even better if it didn't open ports at all, to avoid access by other users on the same machine, but that's probably not possible, is it?)

```
[0] You can now view enter-data-helper in the browser.
[0] 
[0]   Local:            http://localhost:3000
[0]   On Your Network:  http://192.168.x.y:3000
```

**Comment by benj-zen** [comment]
Agreed. Gonna fix it now.

**Comment by benj-zen** [comment]
In development mode opening a port on localhost is the minimum requirement. If you don't want to open ports, use the packaged version.
