### ISSUE TITLE
LUOV

### ISSUE THREAD

**Issue by chrysogonus** [cryptoeng/pqdb#48]
Extending the database by an entry about multivariate-based signature scheme called LUOV.

**Comment by Hennich** [comment]
I already created a branch for luov and inserted the data except benchmarks.

**Comment by franziskuskiefer** [comment]
> I already created a branch for luov and inserted the data except benchmarks.

Then you should've filed an issue for it.

**Comment by benj-zen** [comment]
Added by #59
