### ISSUE TITLE
enter-data-helper does not terminate on close

### ISSUE THREAD

**Issue by dingens** [cryptoeng/pqdb#56]
the electron server should terminate automatically when the window is closed. currently, it seems not to do so reliably, which leads to errors such as `Something is already running on port 3000.` (which makes it impossible to switch branches etc without running a `ps` `grep` `kill` shell marathon ;) )

**Comment by benj-zen** [comment]
The cause of this ist, that in dev mode the electron process is started in parallel with the React dev server. When the electron process is terminated the dev server keeps running. For a quick fix either
1. Launch `yarn electron` without `&`, then CTRL+C terminates the React dev server
or
2. Use the packaged version of enter-data-helper (which doesn't use the server but static content)

**Comment by benj-zen** [comment]
I will however take a look on how to fix this permanently.
