### ISSUE TITLE
Kyber msg sizes

### ISSUE THREAD

**Issue by franziskuskiefer** [cryptoeng/pqdb#8]
Where do these values come from for ct/sig and msg? This might be correct for round 1 but isn't for round 2. Can you check them again?

https://github.com/cryptoeng/pqdb/blob/86a1cddc81e3028830fb70e09e8c13b614362395/encryption/kyber/ccakem/param/512.yaml#L10

**Comment by dingens** [comment]
I got them from the Round 2 documentation (NIST's ZIP package). "Algorithm Specifications And Supporting Documentation Version 2.0" "March 30, 2019". Also fits the numbers here: https://pq-crystals.org/kyber/

What are the numbers you got?

Thanks for reviewing though (we should do this for all the schemes in here so far)

**Comment by franziskuskiefer** [comment]
Yeah everything should be reviewed or at least sanity checked.

> What are the numbers you got?

The file you mention has these numbers :arrow_down: 

![image](https://user-images.githubusercontent.com/890105/75542207-9d6eed00-5a1f-11ea-9c3f-d96cd5d79ba0.png)

**Comment by dingens** [comment]
oops, I didn't read well. I just checked whether there's a `800` :D

**Comment by franziskuskiefer** [comment]
Can this get closed?
